add installer function

diff --git a/0x0F-load_balancer/0-custom_http_response_header b/0x0F-load_balancer/0-custom_http_response_header
--- a/0x0F-load_balancer/0-custom_http_response_header
+++ b/0x0F-load_balancer/0-custom_http_response_header
@@ -1,17 +1,36 @@
 #!/usr/bin/env bash
 # Create Server with header inserted into it
 
-sudo apt-get update -y -qq && \
-	sudo apt-get install nginx -y
+function install () {
+	command -v "$1" &> /dev/null
+	if [[ $? -eq 0 ]]; then
+		sudo apt-get update -y -qq && \
+		sudo apt-get install nginx -y
+	fi
+}
 
-sudo service nginx start
+install nginx
 
 sudo ufw allow 'Nginx HTTP'
 
-sudo chown -R "$USER":"$USER" /var/www/html
-sudo chmod -R 755 /var/www
+if [[ -d /var/www ]]; then
+	sudo chown -R "$USER":"$USER" /var/www
+	sudo chmod -R 755 /var/www
+else
+	sudo mkdir /var/www/
+	sudo chown -R "$USER":"$USER" /var/www
+	sudo chmod -R 755 /var/www
+fi
 
-echo -e "Hello World!" > /var/www/html/index.nginx-debian.html
+for dir in /var/www/{html,error}; do
+	if ! [[ -d "$dir" ]]; then 
+		sudo mkdir -p "$dir"
+	fi
+done;
+
+echo -e "Hello World!" > /var/www/html/index.html
+
+echo -e "Ceci n'est pas une page" > /var/www/html/error_404.html;
 
 service_con=\
 "server {
@@ -38,8 +57,6 @@ service_con=\
 	}
 }"
 
-echo "$service_con" > /etc/nginx/sites-available/default
-
-echo -e "Ceci n'est pas une page" > /var/www/html/error_404.html;
+echo "$service_con" > /etc/nginx/sites-enabled/default
 
 sudo service nginx restart;
